---

- assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version in ["7"]

- name: package is present
  package:
    name:
      - ffmpeg-libs
      - firefox
    state: present

- name: autoconfig does exist
  copy:
    src: firefox.cfg
    dest: /usr/lib64/firefox/

- name: autoconfig is enabled
  copy:
    src: autoconfig.js
    dest: /usr/lib64/firefox/defaults/pref/
